//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fc.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About Us.
        /// </summary>
        public static string footerAbout {
            get {
                return ResourceManager.GetString("footerAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Chosen for you.
        /// </summary>
        public static string footerChosen {
            get {
                return ResourceManager.GetString("footerChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About.
        /// </summary>
        public static string footerLinkAbout {
            get {
                return ResourceManager.GetString("footerLinkAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Categories.
        /// </summary>
        public static string footerLinkCategories {
            get {
                return ResourceManager.GetString("footerLinkCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact.
        /// </summary>
        public static string footerLinkContact {
            get {
                return ResourceManager.GetString("footerLinkContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a How TO.
        /// </summary>
        public static string footerLinkHowTo {
            get {
                return ResourceManager.GetString("footerLinkHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Terms of Use.
        /// </summary>
        public static string footerLinkTerms {
            get {
                return ResourceManager.GetString("footerLinkTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Useful Links.
        /// </summary>
        public static string footerUseful {
            get {
                return ResourceManager.GetString("footerUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a English.
        /// </summary>
        public static string headerEnglish {
            get {
                return ResourceManager.GetString("headerEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a How TO.
        /// </summary>
        public static string headerHowTo {
            get {
                return ResourceManager.GetString("headerHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Italian.
        /// </summary>
        public static string headerItalian {
            get {
                return ResourceManager.GetString("headerItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Language.
        /// </summary>
        public static string headerLanguage {
            get {
                return ResourceManager.GetString("headerLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        public static string headerLogin {
            get {
                return ResourceManager.GetString("headerLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sell.
        /// </summary>
        public static string headerSell {
            get {
                return ResourceManager.GetString("headerSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Signup.
        /// </summary>
        public static string headerSignup {
            get {
                return ResourceManager.GetString("headerSignup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ads.
        /// </summary>
        public static string homeAdsCount {
            get {
                return ResourceManager.GetString("homeAdsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Browse by category.
        /// </summary>
        public static string homeCategory {
            get {
                return ResourceManager.GetString("homeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Locations.
        /// </summary>
        public static string homeCounterLocations {
            get {
                return ResourceManager.GetString("homeCounterLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regular Members.
        /// </summary>
        public static string homeCounterMembers {
            get {
                return ResourceManager.GetString("homeCounterMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Regular Ads.
        /// </summary>
        public static string homeCounterRegular {
            get {
                return ResourceManager.GetString("homeCounterRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Featured Listings.
        /// </summary>
        public static string homeFeatured {
            get {
                return ResourceManager.GetString("homeFeatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ViewMore.
        /// </summary>
        public static string homeViewMore {
            get {
                return ResourceManager.GetString("homeViewMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a About Us.
        /// </summary>
        public static string pageAboutHeaderTitle {
            get {
                return ResourceManager.GetString("pageAboutHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Policy.
        /// </summary>
        public static string pageCookie {
            get {
                return ResourceManager.GetString("pageCookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Faq.
        /// </summary>
        public static string pageFaq {
            get {
                return ResourceManager.GetString("pageFaq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a How To.
        /// </summary>
        public static string pageHowTo {
            get {
                return ResourceManager.GetString("pageHowTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your email here.
        /// </summary>
        public static string placeHolderEmail {
            get {
                return ResourceManager.GetString("placeHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Post is free.
        /// </summary>
        public static string postFreeButton {
            get {
                return ResourceManager.GetString("postFreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sell your products online FOR FREE. It&apos;s easier than you think !.
        /// </summary>
        public static string postFreeSubTitle {
            get {
                return ResourceManager.GetString("postFreeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you get anything for sell ?.
        /// </summary>
        public static string postFreeTitle {
            get {
                return ResourceManager.GetString("postFreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search.
        /// </summary>
        public static string searchBuy {
            get {
                return ResourceManager.GetString("searchBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Welcome To.
        /// </summary>
        public static string searchIntroTitle {
            get {
                return ResourceManager.GetString("searchIntroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Buy and sell used industrial machinery.
        /// </summary>
        public static string searchSubTitle {
            get {
                return ResourceManager.GetString("searchSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aleready a memeber?.
        /// </summary>
        public static string widgetAlreadyMemeber {
            get {
                return ResourceManager.GetString("widgetAlreadyMemeber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Subscribe.
        /// </summary>
        public static string widgetBtnSubscribe {
            get {
                return ResourceManager.GetString("widgetBtnSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Log in your account.
        /// </summary>
        public static string widgetMemberLogin {
            get {
                return ResourceManager.GetString("widgetMemberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Our members always get priority care.
        /// </summary>
        public static string widgetMemberText {
            get {
                return ResourceManager.GetString("widgetMemberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you get anything for sell ?.
        /// </summary>
        public static string widgetPostPromo {
            get {
                return ResourceManager.GetString("widgetPostPromo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sell your products online FOR FREE. It&apos;s easier than you think !.
        /// </summary>
        public static string widgetPostPromoContent {
            get {
                return ResourceManager.GetString("widgetPostPromoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Subscribe for updates.
        /// </summary>
        public static string widgetSubscribe {
            get {
                return ResourceManager.GetString("widgetSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Join our 10,000+ subscribers and get access to the latest templates, freebies, announcements and resources!.
        /// </summary>
        public static string widgetSubscribeContent {
            get {
                return ResourceManager.GetString("widgetSubscribeContent", resourceCulture);
            }
        }
    }
}
