//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_articoli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ma_articoli()
        {
            this.ma_articoli_img = new HashSet<ma_articoli_img>();
        }
    
        public string id_articolo { get; set; }
        public string articolo { get; set; }
        public string descrizione_it { get; set; }
        public string descrizione_en { get; set; }
        public System.DateTime data_pubblicazione { get; set; }
        public Nullable<int> anno_produzione { get; set; }
        public Nullable<decimal> prezzo_richiesto { get; set; }
        public Nullable<decimal> prezzo_di_vendita { get; set; }
        public string valuta { get; set; }
        public string id_utente { get; set; }
        public bool online { get; set; }
        public bool venduto { get; set; }
        public Nullable<decimal> peso { get; set; }
        public Nullable<int> ore_di_lavoro { get; set; }
        public string id_categoria { get; set; }
        public string produttore { get; set; }
        public Nullable<System.DateTime> data_eliminazione { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_articoli_img> ma_articoli_img { get; set; }
        public virtual mc_cat_merc mc_cat_merc { get; set; }
        public virtual ma_articoli_view ma_articoli_view { get; set; }
    }
}
