//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_articoli_view
    {
        public string id_articolo { get; set; }
        public Nullable<int> visite { get; set; }
    
        public virtual ma_articoli ma_articoli { get; set; }
    }
}
