//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_articoli_richieste
    {
        public string id_articolo_richiesta { get; set; }
        public string articolo { get; set; }
        public string descrizione_it { get; set; }
        public string descrizione_en { get; set; }
        public string produttore { get; set; }
        public System.DateTime data_richiesta { get; set; }
        public bool online { get; set; }
        public string email_richiedente { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string nazione { get; set; }
        public string citta { get; set; }
        public string telefono { get; set; }
    }
}
