//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mc_cat_merc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mc_cat_merc()
        {
            this.ma_articoli = new HashSet<ma_articoli>();
        }
    
        public string id_categoria { get; set; }
        public string chiave { get; set; }
        public string descrizione_it { get; set; }
        public string descrizione_en { get; set; }
        public string id_categoria_padre { get; set; }
        public Nullable<short> livello { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ma_articoli> ma_articoli { get; set; }
    }
}
