//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource
    {
        public string Culture { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    }
}
