//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_config
    {
        public string id_config { get; set; }
        public string azienda { get; set; }
        public string about_short_it { get; set; }
        public string about_short_en { get; set; }
        public string terms_it { get; set; }
        public string terms_en { get; set; }
        public string privacy_en { get; set; }
        public string privacy_it { get; set; }
        public string about_it { get; set; }
        public string about_en { get; set; }
    }
}
