//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_pages
    {
        public string id_page { get; set; }
        public string titolo_it { get; set; }
        public string titolo_en { get; set; }
        public string sub_titolo_it { get; set; }
        public string sub_titolo_en { get; set; }
        public string descrizione_it { get; set; }
        public string descrizione_en { get; set; }
    }
}
